version: "3"

services:
    db:
        image: postgres
        container_name: db
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./database/pgdata:/var/lib/postgresql/data
        restart: always
        ports:
            - "5432:5432"
    app:
        build: .
        links:
            - db
        volumes:
            - .:/usr/app
        restart: always
        ports:
            - "3333:3333"
        depends_on:
            - db
        #env_file:
        #    - .env    
        command: bash ./init.sh


